#!/bin/bash

dataset=$1
direction="f2e"

#libtool --mode=execute valgrind ./src/latticelm/latticelm \
./src/latticelm/latticelm \
	--train_file data/fisher-callhome/corpus/plf/${dataset}.es.lat \
	--trans_file data/fisher-callhome/corpus/ldc/${dataset}.en.nopunc.lower \
	--file_format openfst --model_type lextm \
	--using_external_tm data/out/giza-pp/train/${dataset}/model/lex.${direction}
